version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: squaduser
      POSTGRES_PASSWORD: squadpass
      POSTGRES_DB: squaddb
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
